# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DateCalculator_GUI_V1_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(340, 280)
        Form.setMinimumSize(QtCore.QSize(340, 280))
        Form.setMaximumSize(QtCore.QSize(340, 280))
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icosrc/DateCalculator_icon_640x640.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(34, 30, 269, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_start = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_start.setObjectName("checkBox_start")
        self.horizontalLayout_3.addWidget(self.checkBox_start)
        self.date_edit_start = QtWidgets.QDateEdit(self.layoutWidget)
        self.date_edit_start.setObjectName("date_edit_start")
        self.horizontalLayout_3.addWidget(self.date_edit_start)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_stop = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_stop.setObjectName("checkBox_stop")
        self.horizontalLayout_2.addWidget(self.checkBox_stop)
        self.date_edit_stop = QtWidgets.QDateEdit(self.layoutWidget)
        self.date_edit_stop.setObjectName("date_edit_stop")
        self.horizontalLayout_2.addWidget(self.date_edit_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_days = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_days.setObjectName("checkBox_days")
        self.horizontalLayout.addWidget(self.checkBox_days)
        self.line_days = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_days.setObjectName("line_days")
        self.horizontalLayout.addWidget(self.line_days)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(32, 150, 271, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_status = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_2.addWidget(self.label_status)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setMinimumSize(QtCore.QSize(251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DateCalculator V1.0"))
        self.checkBox_start.setText(_translate("Form", "计划开工日期："))
        self.checkBox_stop.setText(_translate("Form", "计划竣工日期："))
        self.checkBox_days.setText(_translate("Form", "计 划 工 期 ："))
        self.label.setText(_translate("Form", "天"))
        self.label_status.setText(_translate("Form", "状态显示"))
        self.pushButton.setText(_translate("Form", "开始计算"))
import DateCalculator_src_V1_0
